###
POST http://localhost:3000/api/product
Content-Type: application/json

{
    "name": "talo",
    "seller_id": "6912e02b70323bdb4045f327",
    "start_price": 1000,
    "current_price": 35000,
    "total_bids": 10,
    "status": "active",
    "category_id": "691158f1635fde90d067cb48"
}

###

// GET ALL PRODUCT
GET http://localhost:3000/api/product
Content-Type: application/json

###

// GET 
GET http://localhost:3000/api/product/69074dd92438b6fadd1a1ea4
Content-Type: application/json
###

// GET top 5 price
GET http://localhost:3000/api/product/top5/price
Content-Type: application/json

###

// GET top 5 ending
GET http://localhost:3000/api/product/top5/ending
Content-Type: application/json

###

// GET top 5 bid
GET http://localhost:3000/api/product/top5/bid
Content-Type: application/json

###


POST http://localhost:3000/api/product
Content-Type: application/json

{
  "name": "Cool Bees",
  "description": "Comfortable running shoes",
  "seller_id": "6912e02b70323bdb4045f327",
  "start_price": 1000,
  "bid_step": 50,
  "buy_now_price": 2000,
  "current_price": 1000,
  "status": "active",
  "slug": "cool-shoes",
  "is_autobid": false,
  "allow_unrated_bidders": true,
  "image_url": [
    "https://res.cloudinary.com/onlineauctionproject/image/upload/v1762849948/BeeCorn_xnvm4t.png",
    "https://res.cloudinary.com/onlineauctionproject/image/upload/v1762849947/Bee_oftwpg.png"
  ]
}

###
DELETE http://localhost:3000/api/product/6912f6e273d922eeb49b20d3

###

GET http://localhost:3000/api/product/seller/6912e02b70323bdb4045f327
Content-Type: application/json

###
PATCH http://localhost:3000/api/product/69158b214aed3ca92ad831f3
Content-Type: application/json

{
    "total_bids": 35,
    "status": "ended"
}
###
GET http://localhost:3000/api/product/by-category/691158f1635fde90d067cb48
