###
POST http://localhost:3000/api/bids
Content-Type: application/json

{
  "product_id": "69111c5306251b39d3acd669",
  "bidder_id": "69111e8a06251b39d3acd8f9",
  "price": 10700000
}


### 
GET http://localhost:3000/api/bids/69111c5306251b39d3acd669


### 
GET http://localhost:3000/api/bids


### 
PUT http://localhost:3000/api/bids/6730b2e8c5e9a9f8d3d11122
Content-Type: application/json

{
  "price": 11000000
}


### 
DELETE http://localhost:3000/api/bids/6730b2e8c5e9a9f8d3d11122
