@dienTu = 69343d591ade09a6678819e5
@thoiTrang = 69343d7a1ade09a6678819e7
@dongHo = 69343d871ade09a6678819e9
@xeCo = 69343d951ade09a6678819eb
@noiThat = 69343e321ade09a6678819ed

### Điện thoại
POST http://localhost:3000/api/category
Content-Type: application/json

{
  "category_id": "{{dienTu}}",
  "name": "Điện thoại",
  "slug": "dien-thoai"
}

###
POST http://localhost:3000/api/category
Content-Type: application/json

{
  "category_id": "{{dienTu}}",
  "name": "Laptop",
  "slug": "laptop"
}

###
POST http://localhost:3000/api/category
Content-Type: application/json

{
  "category_id": "{{thoiTrang}}",
  "name": "Áo thun",
  "slug": "ao-thun"
}

###
POST http://localhost:3000/api/category
Content-Type: application/json

{
  "category_id": "{{thoiTrang}}",
  "name": "Giày",
  "slug": "giay"
}

###
POST http://localhost:3000/api/category
Content-Type: application/json

{
  "category_id": "{{dongHo}}",
  "name": "Rolex",
  "slug": "rolex"
}

###
POST http://localhost:3000/api/category
Content-Type: application/json

{
  "category_id": "{{dongHo}}",
  "name": "Casio",
  "slug": "casio"
}

###
POST http://localhost:3000/api/category
Content-Type: application/json

{
  "category_id": "{{xeCo}}",
  "name": "SH",
  "slug": "sh"
}

###
POST http://localhost:3000/api/category
Content-Type: application/json

{
  "category_id": "{{xeCo}}",
  "name": "Trực thăng",
  "slug": "truc-thang"
}

###
POST http://localhost:3000/api/category
Content-Type: application/json

{
  "category_id": "{{noiThat}}",
  "name": "Bàn ghế",
  "slug": "ban-ghe"
}

###
POST http://localhost:3000/api/category
Content-Type: application/json

{
  "category_id": "{{noiThat}}",
  "name": "Trang trí",
  "slug": "trang-tri"
}