###
POST http://localhost:3000/api/watchlist
Content-Type: application/json

{
    "user_id": "69074d222438b6fadd1a1ea2",
    "product_id": ["69074dd92438b6fadd1a1ea4",
    "6912f7b57e185fa911aa95ca"]
}

###

//GET ALL WATCHLIST
GET http://localhost:3000/api/watchlist
Content-Type: application/json

###

GET http://localhost:3000/api/watchlist/user/
Content-Type: application/json

###

GET http://localhost:3000/api/watchlist/69074d222438b6fadd1a1ea2
Content-Type: application/json

###
// ADD PRODUCT
PATCH http://localhost:3000/api/watchlist/690b56766d0100a54cbca32a
Content-Type: application/json

{
    "product_id": "6912f7b57e185fa911aa95ca"
}

###
// REMOVE PRODUCT
DELETE http://localhost:3000/api/watchlist/69074d222438b6fadd1a1ea2/6912f7b57e185fa911aa95ca
Content-Type: application/json

###

DELETE http://localhost:3000/api/watchlist/69074d222438b6fadd1a1ea2
Content-Type: application/json